baseurl: "/"
title: "Stackbit Exto Theme"
page_load_js: "assets/js/main.js"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Exto
    has_nav: true
  footer:
    content: "&copy; Stackbit-Exto. All rights reserved."
    links:
      - text: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    has_social: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
